name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
            "3.7.17",
            "3.8.18",
            "3.10.13",
            "3.13.0-alpha.4",
            "pypy3.9",
            "graalpy-22.3" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip deps
      - name: Install dependencies
        run: |
          python -m pip install -f requirements_publish.txt
      - name: Run tests
        run: tox

